{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "bf7a9bd9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-04 14:15:45.201 No runtime found, using MemoryCacheStorageManager\n",
      "2026-03-04 14:15:45.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.223 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.226 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.227 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.231 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.235 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.244 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.247 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.248 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.264 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.289 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.292 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.293 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.295 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.297 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.297 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.298 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.299 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.301 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.301 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.302 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.303 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.303 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.310 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.310 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.320 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.320 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.331 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.338 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.342 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.342 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.343 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.344 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.344 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.346 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.348 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.348 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.348 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.350 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.351 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.351 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.362 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.362 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.362 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.366 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-04 14:15:45.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.372 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.377 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:45.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.199 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-04 14:15:50.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.204 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-04 14:15:50.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.209 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-03-04 14:15:50.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.249 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.425 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.536 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.538 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.538 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.751 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.752 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.755 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-04 14:15:50.755 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# app.py\n",
    "# Streamlit app: Structured Products Simulator (Phoenix / Autocall mechanics) with:\n",
    "# - Manual mode (user inputs S0, vol, corr)\n",
    "# - Market data mode (Yahoo Finance via yfinance -> S0, hist vol, hist corr)\n",
    "# - Multi-asset (1..5), basket (worst-of / best-of / average / weighted)\n",
    "# - Phoenix-style payoff: conditional coupons (+ optional memory), autocall, maturity barrier\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import streamlit as st\n",
    "import matplotlib.pyplot as plt\n",
    "import yfinance as yf\n",
    "\n",
    "# ----------------------------\n",
    "# Utils: numerics\n",
    "# ----------------------------\n",
    "def ensure_3d_paths(paths: np.ndarray) -> np.ndarray:\n",
    "    paths = np.asarray(paths, float)\n",
    "    if paths.ndim == 2:  # (n_sims, n_steps+1) -> (n_sims, n_steps+1, 1)\n",
    "        return paths[:, :, None]\n",
    "    return paths\n",
    "\n",
    "def nearest_psd_corr(mat: np.ndarray, eps: float = 1e-10) -> np.ndarray:\n",
    "    \"\"\"Project a symmetric matrix to a PSD correlation matrix (simple eigenvalue clipping).\"\"\"\n",
    "    A = np.asarray(mat, float)\n",
    "    A = 0.5 * (A + A.T)\n",
    "    np.fill_diagonal(A, 1.0)\n",
    "\n",
    "    vals, vecs = np.linalg.eigh(A)\n",
    "    vals = np.clip(vals, eps, None)\n",
    "    B = vecs @ np.diag(vals) @ vecs.T\n",
    "    B = 0.5 * (B + B.T)\n",
    "\n",
    "    # Re-normalize to correlation (diagonal = 1)\n",
    "    d = np.sqrt(np.clip(np.diag(B), eps, None))\n",
    "    C = B / (d[:, None] * d[None, :])\n",
    "    np.fill_diagonal(C, 1.0)\n",
    "    return 0.5 * (C + C.T)\n",
    "\n",
    "def cholesky_safe(corr: np.ndarray) -> np.ndarray:\n",
    "    \"\"\"Cholesky with fallback to nearest PSD correlation matrix.\"\"\"\n",
    "    try:\n",
    "        return np.linalg.cholesky(corr)\n",
    "    except np.linalg.LinAlgError:\n",
    "        corr_psd = nearest_psd_corr(corr)\n",
    "        return np.linalg.cholesky(corr_psd)\n",
    "\n",
    "# ----------------------------\n",
    "# Market model: correlated GBM\n",
    "# ----------------------------\n",
    "def simulate_correlated_gbm(\n",
    "    S0: np.ndarray,\n",
    "    r: float,\n",
    "    q: np.ndarray,\n",
    "    sigma: np.ndarray,\n",
    "    corr: np.ndarray,\n",
    "    T: float,\n",
    "    n_steps: int,\n",
    "    n_sims: int,\n",
    "    seed: int = 42,\n",
    ") -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Returns paths of shape (n_sims, n_steps+1, n_assets).\n",
    "    Risk-neutral GBM: dS = (r-q)S dt + sigma S dW\n",
    "    \"\"\"\n",
    "    rng = np.random.default_rng(int(seed))\n",
    "\n",
    "    S0 = np.asarray(S0, float)\n",
    "    q = np.asarray(q, float)\n",
    "    sigma = np.asarray(sigma, float)\n",
    "\n",
    "    n_assets = S0.size\n",
    "    dt = T / n_steps\n",
    "\n",
    "    L = cholesky_safe(corr)\n",
    "\n",
    "    Z = rng.standard_normal((n_sims, n_steps, n_assets))\n",
    "    dW = Z @ L.T  # correlate across assets\n",
    "\n",
    "    drift = (r - q - 0.5 * sigma**2) * dt                  # (n_assets,)\n",
    "    diff = sigma * np.sqrt(dt) * dW                        # (n_sims, n_steps, n_assets)\n",
    "\n",
    "    log_increments = drift[None, None, :] + diff\n",
    "    log_paths = np.cumsum(log_increments, axis=1)          # (n_sims, n_steps, n_assets)\n",
    "\n",
    "    paths = np.empty((n_sims, n_steps + 1, n_assets))\n",
    "    paths[:, 0, :] = S0\n",
    "    paths[:, 1:, :] = S0[None, None, :] * np.exp(log_paths)\n",
    "    return paths\n",
    "\n",
    "# ----------------------------\n",
    "# Basket engine\n",
    "# ----------------------------\n",
    "def basket_ratio(St_t: np.ndarray, S0: np.ndarray, kind: str = \"worst-of\", weights=None) -> np.ndarray:\n",
    "    \"\"\"\n",
    "    St_t: (n_sims, n_assets) prices at time t\n",
    "    S0:   (n_assets,)\n",
    "    returns: (n_sims,) basket performance ratios\n",
    "    \"\"\"\n",
    "    S0 = np.asarray(S0, float)\n",
    "    R = St_t / S0[None, :]\n",
    "\n",
    "    kind = kind.lower()\n",
    "    if kind == \"worst-of\":\n",
    "        return np.min(R, axis=1)\n",
    "    if kind == \"best-of\":\n",
    "        return np.max(R, axis=1)\n",
    "    if kind == \"average\":\n",
    "        return np.mean(R, axis=1)\n",
    "    if kind == \"weighted\":\n",
    "        w = np.asarray(weights, float)\n",
    "        w = w / np.sum(w)\n",
    "        return R @ w\n",
    "\n",
    "    raise ValueError(\"kind must be: worst-of / best-of / average / weighted\")\n",
    "\n",
    "def build_obs_idx(T: float, steps_per_year: int, obs_per_year: int) -> np.ndarray:\n",
    "    n_steps = int(round(T * steps_per_year))\n",
    "    obs_step = int(round(steps_per_year / obs_per_year))\n",
    "    obs_idx = np.arange(obs_step, n_steps + 1, obs_step, dtype=int)\n",
    "    obs_idx = obs_idx[obs_idx <= n_steps]\n",
    "    return obs_idx\n",
    "\n",
    "# ----------------------------\n",
    "# Product: Phoenix (coupon + memory + autocall + maturity barrier)\n",
    "# ----------------------------\n",
    "def phoenix_payoff(\n",
    "    paths: np.ndarray,\n",
    "    S0: np.ndarray,\n",
    "    nominal: float,\n",
    "    obs_idx: np.ndarray,\n",
    "    coupon_rate_per_obs: float,\n",
    "    coupon_trigger: float,\n",
    "    call_trigger: float,\n",
    "    barrier: float,\n",
    "    basket_kind: str = \"worst-of\",\n",
    "    weights=None,\n",
    "    memory: bool = True,\n",
    ") -> tuple[np.ndarray, np.ndarray, np.ndarray]:\n",
    "    \"\"\"\n",
    "    paths: (n_sims, n_steps+1, n_assets)\n",
    "    Returns:\n",
    "      payoff: (n_sims,)\n",
    "      autocalled: (n_sims,) bool\n",
    "      autocall_obs: (n_sims,) int obs number (0-based) or -1\n",
    "    \"\"\"\n",
    "    paths = ensure_3d_paths(paths)\n",
    "    n_sims, _, n_assets = paths.shape\n",
    "\n",
    "    S0 = np.asarray(S0, float)\n",
    "    if S0.ndim == 0:\n",
    "        S0 = np.array([float(S0)])\n",
    "    if S0.size != n_assets:\n",
    "        raise ValueError(\"S0 must match n_assets in paths.\")\n",
    "\n",
    "    payoff = np.zeros(n_sims)\n",
    "    autocalled = np.zeros(n_sims, dtype=bool)\n",
    "    autocall_obs = np.full(n_sims, -1, dtype=int)\n",
    "\n",
    "    accrued = np.zeros(n_sims)  # coupon memory bucket\n",
    "\n",
    "    for k, t in enumerate(obs_idx):\n",
    "        alive = ~autocalled\n",
    "        if not np.any(alive):\n",
    "            break\n",
    "\n",
    "        St = paths[alive, t, :]\n",
    "        ratio = basket_ratio(St, S0, kind=basket_kind, weights=weights)\n",
    "\n",
    "        # Coupon condition\n",
    "        coupon_ok = ratio >= coupon_trigger\n",
    "        if memory:\n",
    "            accrued_alive = accrued[alive] + nominal * coupon_rate_per_obs\n",
    "            payoff[alive] += accrued_alive * coupon_ok\n",
    "            accrued[alive] = accrued_alive * (~coupon_ok)\n",
    "        else:\n",
    "            payoff[alive] += (nominal * coupon_rate_per_obs) * coupon_ok\n",
    "\n",
    "        # Autocall condition\n",
    "        call_ok = ratio >= call_trigger\n",
    "        idx_alive = np.where(alive)[0]\n",
    "        called_idx = idx_alive[call_ok]\n",
    "        if called_idx.size:\n",
    "            autocalled[called_idx] = True\n",
    "            autocall_obs[called_idx] = k\n",
    "            payoff[called_idx] += nominal\n",
    "\n",
    "    # Maturity payoff for remaining\n",
    "    alive = ~autocalled\n",
    "    if np.any(alive):\n",
    "        ST = paths[alive, -1, :]\n",
    "        ratio_T = basket_ratio(ST, S0, kind=basket_kind, weights=weights)\n",
    "        protected = ratio_T >= barrier\n",
    "        payoff[alive] += np.where(protected, nominal, nominal * ratio_T)\n",
    "\n",
    "    return payoff, autocalled, autocall_obs\n",
    "\n",
    "# ----------------------------\n",
    "# Metrics\n",
    "# ----------------------------\n",
    "def summarize_metrics(payoff: np.ndarray, autocalled: np.ndarray, autocall_obs: np.ndarray, obs_per_year: int) -> pd.DataFrame:\n",
    "    payoff = np.asarray(payoff, float)\n",
    "    autocalled = np.asarray(autocalled, bool)\n",
    "\n",
    "    out = {\n",
    "        \"Expected payoff\": float(np.mean(payoff)),\n",
    "        \"Median payoff\": float(np.median(payoff)),\n",
    "        \"P(Autocall)\": float(np.mean(autocalled)),\n",
    "        \"5% quantile\": float(np.quantile(payoff, 0.05)),\n",
    "        \"1% quantile\": float(np.quantile(payoff, 0.01)),\n",
    "    }\n",
    "    calls = autocall_obs[autocall_obs >= 0]\n",
    "    if calls.size:\n",
    "        out[\"Expected autocall time (years)\"] = float(np.mean((calls + 1) / obs_per_year))\n",
    "    else:\n",
    "        out[\"Expected autocall time (years)\"] = np.nan\n",
    "\n",
    "    return pd.DataFrame(out, index=[\"Value\"]).T\n",
    "\n",
    "# ----------------------------\n",
    "# Market data (Yahoo Finance)\n",
    "# ----------------------------\n",
    "@st.cache_data(show_spinner=False)\n",
    "def fetch_market_params(tickers: list[str], lookback_years: int) -> tuple[np.ndarray, np.ndarray, np.ndarray, pd.DataFrame]:\n",
    "    end = pd.Timestamp.today().tz_localize(None)\n",
    "    start = end - pd.DateOffset(years=int(lookback_years))\n",
    "\n",
    "    px = yf.download(tickers, start=start, end=end, auto_adjust=True, progress=False)[\"Close\"]\n",
    "    if isinstance(px, pd.Series):  # single ticker returns Series\n",
    "        px = px.to_frame()\n",
    "\n",
    "    px = px.dropna(how=\"all\").dropna(axis=1, how=\"any\")\n",
    "    if px.shape[1] == 0:\n",
    "        raise ValueError(\"No usable price data returned (check tickers).\")\n",
    "\n",
    "    rets = px.pct_change().dropna()\n",
    "    S0 = px.iloc[-1].values\n",
    "    sigma = rets.std().values * np.sqrt(252)\n",
    "    corr = rets.corr().values\n",
    "    return S0, sigma, corr, px\n",
    "\n",
    "# ----------------------------\n",
    "# Streamlit UI\n",
    "# ----------------------------\n",
    "st.set_page_config(page_title=\"Structured Products Simulator\", layout=\"wide\")\n",
    "st.title(\"Structured Products Simulator (Phoenix) — Manual + Market Data\")\n",
    "\n",
    "with st.sidebar:\n",
    "    st.header(\"Mode\")\n",
    "    mode = st.radio(\"Parameter source\", [\"Manual parameters\", \"Market data (Yahoo Finance)\"], index=0)\n",
    "\n",
    "    st.header(\"Product\")\n",
    "    nominal = st.number_input(\"Nominal\", min_value=1.0, value=1000.0, step=100.0)\n",
    "    T = st.number_input(\"Maturity (years)\", min_value=0.25, value=3.0, step=0.25)\n",
    "    steps_per_year = st.selectbox(\"Simulation steps/year\", [252, 52, 12], index=0)\n",
    "    obs_per_year = st.selectbox(\"Observation frequency/year\", [12, 4, 2, 1], index=1)\n",
    "\n",
    "    coupon_pa = st.number_input(\"Coupon p.a. (e.g. 0.10 = 10%)\", min_value=0.0, value=0.10, step=0.01)\n",
    "    coupon_trigger = st.number_input(\"Coupon trigger (ratio)\", min_value=0.0, max_value=2.0, value=0.70, step=0.01)\n",
    "    call_trigger = st.number_input(\"Autocall trigger (ratio)\", min_value=0.0, max_value=2.0, value=1.00, step=0.01)\n",
    "    barrier = st.number_input(\"Maturity barrier (ratio)\", min_value=0.0, max_value=2.0, value=0.60, step=0.01)\n",
    "    memory = st.checkbox(\"Memory coupon\", value=True)\n",
    "\n",
    "    st.header(\"Basket\")\n",
    "    basket_kind = st.selectbox(\"Basket type\", [\"worst-of\", \"best-of\", \"average\", \"weighted\"], index=0)\n",
    "\n",
    "    st.header(\"Rates / Dividends\")\n",
    "    r = st.number_input(\"Risk-free rate r\", value=0.02, step=0.005)\n",
    "    use_q = st.checkbox(\"Set dividend yields q\", value=False)\n",
    "\n",
    "    st.header(\"Monte Carlo\")\n",
    "    n_sims = st.slider(\"Number of simulations\", 5000, 120000, 30000, step=5000)\n",
    "    seed = st.number_input(\"Random seed\", value=42, step=1)\n",
    "\n",
    "# --- Inputs for assets (manual or market)\n",
    "tickers = None\n",
    "px_preview = None\n",
    "\n",
    "if mode == \"Market data (Yahoo Finance)\":\n",
    "    with st.sidebar:\n",
    "        st.subheader(\"Market data settings\")\n",
    "        tickers_str = st.text_input(\"Tickers (comma-separated)\", value=\"AAPL,MSFT\")\n",
    "        lookback_years = st.slider(\"Lookback (years)\", 1, 10, 3)\n",
    "\n",
    "    tickers = [t.strip().upper() for t in tickers_str.split(\",\") if t.strip()]\n",
    "    if len(tickers) == 0:\n",
    "        st.error(\"Please enter at least 1 ticker.\")\n",
    "        st.stop()\n",
    "\n",
    "    try:\n",
    "        S0, sigma, corr, px_preview = fetch_market_params(tickers, lookback_years)\n",
    "    except Exception as e:\n",
    "        st.error(f\"Market data error: {e}\")\n",
    "        st.stop()\n",
    "\n",
    "    n_assets = len(S0)\n",
    "    q = np.zeros(n_assets)  # MVP: keep q = 0 (you can extend later)\n",
    "\n",
    "    if use_q:\n",
    "        # allow overriding q manually even in market mode\n",
    "        with st.sidebar:\n",
    "            st.subheader(\"Dividend yields q (override)\")\n",
    "            q_list = []\n",
    "            for i in range(n_assets):\n",
    "                q_list.append(st.number_input(f\"q {tickers[i]}\", value=0.00, step=0.005, key=f\"q_m_{i}\"))\n",
    "            q = np.array(q_list, float)\n",
    "\n",
    "else:\n",
    "    with st.sidebar:\n",
    "        st.subheader(\"Manual asset settings\")\n",
    "        n_assets = st.number_input(\"Number of underlyings\", min_value=1, max_value=5, value=2, step=1)\n",
    "\n",
    "        S0_list, sigma_list, q_list = [], [], []\n",
    "        for i in range(int(n_assets)):\n",
    "            st.markdown(f\"**Asset {i+1}**\")\n",
    "            S0_list.append(st.number_input(f\"S0 {i+1}\", value=100.0, step=1.0, key=f\"S0_{i}\"))\n",
    "            sigma_list.append(st.number_input(f\"Vol (sigma) {i+1}\", value=0.25, step=0.01, key=f\"sig_{i}\"))\n",
    "            if use_q:\n",
    "                q_list.append(st.number_input(f\"q {i+1}\", value=0.00, step=0.005, key=f\"q_{i}\"))\n",
    "            else:\n",
    "                q_list.append(0.0)\n",
    "\n",
    "        S0 = np.array(S0_list, float)\n",
    "        sigma = np.array(sigma_list, float)\n",
    "        q = np.array(q_list, float)\n",
    "\n",
    "        st.subheader(\"Correlation matrix\")\n",
    "        corr_df = pd.DataFrame(\n",
    "            np.eye(int(n_assets)),\n",
    "            index=[f\"A{i+1}\" for i in range(int(n_assets))],\n",
    "            columns=[f\"A{i+1}\" for i in range(int(n_assets))],\n",
    "        )\n",
    "        corr_df = st.data_editor(corr_df, use_container_width=True, key=\"corr_editor\")\n",
    "        corr = corr_df.to_numpy()\n",
    "\n",
    "# --- Basket weights (if weighted)\n",
    "weights = None\n",
    "if basket_kind == \"weighted\":\n",
    "    with st.sidebar:\n",
    "        st.subheader(\"Weights\")\n",
    "        w_list = []\n",
    "        labels = tickers if tickers else [f\"A{i+1}\" for i in range(int(n_assets))]\n",
    "        for i, lab in enumerate(labels):\n",
    "            w_list.append(st.number_input(f\"Weight {lab}\", value=1.0, step=0.1, key=f\"w_{i}\"))\n",
    "        weights = np.array(w_list, float)\n",
    "\n",
    "# --- Run simulation & product\n",
    "n_steps = int(round(T * steps_per_year))\n",
    "obs_idx = build_obs_idx(T, steps_per_year, int(obs_per_year))\n",
    "coupon_rate_per_obs = coupon_pa / int(obs_per_year)\n",
    "\n",
    "with st.spinner(\"Simulating paths and pricing...\"):\n",
    "    paths = simulate_correlated_gbm(\n",
    "        S0=S0,\n",
    "        r=float(r),\n",
    "        q=q,\n",
    "        sigma=sigma,\n",
    "        corr=corr,\n",
    "        T=float(T),\n",
    "        n_steps=n_steps,\n",
    "        n_sims=int(n_sims),\n",
    "        seed=int(seed),\n",
    "    )\n",
    "\n",
    "    payoff, autocalled, autocall_obs = phoenix_payoff(\n",
    "        paths=paths,\n",
    "        S0=S0,\n",
    "        nominal=float(nominal),\n",
    "        obs_idx=obs_idx,\n",
    "        coupon_rate_per_obs=float(coupon_rate_per_obs),\n",
    "        coupon_trigger=float(coupon_trigger),\n",
    "        call_trigger=float(call_trigger),\n",
    "        barrier=float(barrier),\n",
    "        basket_kind=basket_kind,\n",
    "        weights=weights,\n",
    "        memory=bool(memory),\n",
    "    )\n",
    "\n",
    "metrics_df = summarize_metrics(payoff, autocalled, autocall_obs, int(obs_per_year))\n",
    "\n",
    "# ----------------------------\n",
    "# Output section\n",
    "# ----------------------------\n",
    "col1, col2 = st.columns([1, 2])\n",
    "\n",
    "with col1:\n",
    "    st.subheader(\"Inputs (summary)\")\n",
    "    labels = tickers if tickers else [f\"A{i+1}\" for i in range(len(S0))]\n",
    "    df_params = pd.DataFrame(\n",
    "        {\"S0\": S0, \"sigma\": sigma, \"q\": q},\n",
    "        index=labels\n",
    "    )\n",
    "    st.dataframe(df_params, use_container_width=True)\n",
    "    st.caption(\"Correlation matrix used (may be adjusted to PSD internally if needed).\")\n",
    "    st.dataframe(pd.DataFrame(corr, index=labels, columns=labels), use_container_width=True)\n",
    "\n",
    "    st.subheader(\"Key metrics\")\n",
    "    st.dataframe(metrics_df, use_container_width=True)\n",
    "\n",
    "    out_df = pd.DataFrame(\n",
    "        {\n",
    "            \"payoff\": payoff,\n",
    "            \"autocalled\": autocalled.astype(int),\n",
    "            \"autocall_obs\": autocall_obs,\n",
    "        }\n",
    "    )\n",
    "    st.download_button(\n",
    "        \"Download simulation results (CSV)\",\n",
    "        data=out_df.to_csv(index=False),\n",
    "        file_name=\"simulation_results.csv\",\n",
    "        mime=\"text/csv\",\n",
    "        use_container_width=True,\n",
    "    )\n",
    "\n",
    "with col2:\n",
    "    st.subheader(\"Payoff distribution\")\n",
    "    fig = plt.figure()\n",
    "    plt.hist(payoff, bins=80)\n",
    "    plt.xlabel(\"Payoff\")\n",
    "    plt.ylabel(\"Frequency\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "    st.subheader(\"Autocall timing (obs index)\")\n",
    "    calls = autocall_obs[autocall_obs >= 0]\n",
    "    fig2 = plt.figure()\n",
    "    if calls.size:\n",
    "        plt.hist(calls, bins=np.arange(0, len(obs_idx) + 1) - 0.5)\n",
    "        plt.xlabel(\"Observation number (0-based)\")\n",
    "        plt.ylabel(\"Count\")\n",
    "    else:\n",
    "        plt.text(0.5, 0.5, \"No autocalls in this run.\", ha=\"center\", va=\"center\")\n",
    "        plt.axis(\"off\")\n",
    "    st.pyplot(fig2)\n",
    "\n",
    "    st.subheader(\"Sample paths (first 30 sims, basket ratio)\")\n",
    "    # plot basket ratio through time for a few simulations (cleaner than plotting all assets)\n",
    "    paths3 = ensure_3d_paths(paths)\n",
    "    tgrid = np.linspace(0, float(T), n_steps + 1)\n",
    "    fig3 = plt.figure()\n",
    "    m = min(30, paths3.shape[0])\n",
    "    for i in range(m):\n",
    "        ratio_line = basket_ratio(paths3[i, :, :], S0, kind=basket_kind, weights=weights)\n",
    "        plt.plot(tgrid, ratio_line, linewidth=0.8)\n",
    "    plt.axhline(coupon_trigger, linestyle=\"--\")\n",
    "    plt.axhline(call_trigger, linestyle=\"--\")\n",
    "    plt.axhline(barrier, linestyle=\"--\")\n",
    "    plt.xlabel(\"Time (years)\")\n",
    "    plt.ylabel(\"Basket ratio\")\n",
    "    st.pyplot(fig3)\n",
    "\n",
    "if px_preview is not None:\n",
    "    st.subheader(\"Market data preview (auto-adjusted close)\")\n",
    "    st.line_chart(px_preview)\n",
    "\n",
    "st.caption(\n",
    "    \"Notes: This is a simplified Monte Carlo simulator (GBM + historical vol/corr in market mode). \"\n",
    "    \"Real desk pricing uses implied vol surfaces, dividend curves, and calibrated rate curves.\"\n",
    ")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
